import { useCallback, useEffect, useRef, useState } from 'react';
import { api, base } from './api';
import './painel.css';

const pages = ['Visão geral', 'Reservas', 'Calendário', 'Acomodações', 'Sincronização', 'Configurações'];
const slugs = ['inicio', 'reservas', 'calendario', 'acomodacoes', 'sincronizacao', 'configuracoes'];
const channels = ['direto', 'airbnb', 'booking', 'expedia', 'outro'];
const statuses = ['pendente', 'confirmada', 'checkin', 'checkout', 'cancelada'];
const money = n => Number(n || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const date = d => d ? String(d).slice(0, 10).split('-').reverse().join('/') : '—';
const id = v => v?._id || v?.id || v;
function Field({ label, name, type = 'text', value, onChange, options, required = false, ...props }) {
  return <label className="p-field">{label}{options ? <select aria-label={label} name={name} value={value ?? ''} onChange={onChange} required={required} {...props}>{options.map(o => <option key={typeof o === 'string' ? o : o.value} value={typeof o === 'string' ? o : o.value}>{typeof o === 'string' ? o : o.label}</option>)}</select> : <input aria-label={label} name={name} type={type} value={value ?? ''} onChange={onChange} required={required} {...props} />}</label>;
}
function Editor({ title, fields, initial, submit, label = 'Salvar', onCancel, disabled }) {
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => setForm(initial), [initial]);
  return <form className="p-card p-editor" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await submit(form); } catch (ex) { setError(ex.message); } finally { setBusy(false); } }}>
    {title && <h2>{title}</h2>}<div className="p-fields">{fields.map(f => <Field key={f.name} {...f} disabled={disabled} value={form[f.name]} onChange={e => setForm({ ...form, [f.name]: f.type === 'number' ? Number(e.target.value) : e.target.value })} />)}</div>
    {error && <p role="alert" className="p-error">{error}</p>}{!disabled && <div className="p-actions"><button disabled={busy}>{busy ? 'Salvando…' : label}</button>{onCancel && <button type="button" className="secondary" onClick={onCancel}>Fechar</button>}</div>}
  </form>;
}
const roomOptions = rooms => [{ value: '', label: 'Selecione uma acomodação' }, ...rooms.map(a => ({ value: id(a), label: a.nome }))];
const roomFields = [{ label: 'Nome', name: 'nome', required: true }, { label: 'Tipo', name: 'tipo', options: ['standard', 'luxo', 'suite', 'chalé', 'bangalô', 'outro'] }, { label: 'Capacidade', name: 'maxHospedes', type: 'number', min: 1, max: 20, required: true }, { label: 'Camas', name: 'camas', required: true }, { label: 'Diária padrão (R$)', name: 'valorPadrao', type: 'number', min: 0, step: '.01', required: true }, { label: 'Situação', name: 'status', options: ['ativa', 'inativa', 'manutencao'] }, { label: 'Descrição', name: 'descricao' }];
const freshRoom = { nome: '', tipo: 'suite', maxHospedes: 2, camas: '', valorPadrao: 0, status: 'ativa', descricao: '' };

export default function Painel() {
  const requestGeneration = useRef(0);
  const [user, setUser] = useState(null); const [authLoading, setAuthLoading] = useState(!!sessionStorage.getItem('recanto-token'));
  const [page, setPage] = useState(() => Math.max(0, slugs.indexOf(location.pathname.split('/')[2])));
  const [data, setData] = useState({}); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [editor, setEditor] = useState(null); const [online, setOnline] = useState(navigator.onLine);
  const [filters, setFilters] = useState({ status: '', canal: '', inicio: '', fim: '' });
  const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const write = user && user.role !== 'visualizacao';
  useEffect(() => {
    const expire = () => { requestGeneration.current++; setLoading(false); setEditor(null); setUser(null); setData({}); setNotice(''); setError('Sua sessão expirou. Entre novamente.'); };
    const back = () => { requestGeneration.current++; setData({}); setPage(Math.max(0, slugs.indexOf(location.pathname.split('/')[2]))); setEditor(null); };
    const connection = () => setOnline(navigator.onLine);
    window.addEventListener('recanto-expired', expire); window.addEventListener('popstate', back); window.addEventListener('online', connection); window.addEventListener('offline', connection);
    const restoredToken = sessionStorage.getItem('recanto-token'); let mounted = true; const restoredActive = () => mounted && restoredToken === sessionStorage.getItem('recanto-token');
    if (restoredToken) api('/auth/me').then(r => { if (restoredActive()) setUser(r.usuario); }).catch(e => { if (restoredActive()) setError(e.message); }).finally(() => { if (mounted) setAuthLoading(false); });
    return () => { mounted = false; window.removeEventListener('recanto-expired', expire); window.removeEventListener('popstate', back); window.removeEventListener('online', connection); window.removeEventListener('offline', connection); };
  }, []);
  const load = useCallback(async () => {
    if (!user) return; const generation = ++requestGeneration.current; const token = sessionStorage.getItem('recanto-token'); const valid = () => generation === requestGeneration.current && token === sessionStorage.getItem('recanto-token'); setLoading(true); setError('');
    try {
      const entries = page === 0 ? [['stats', '/dashboard/stats'], ['alerts', '/alertas?resolvido=false']] : page === 1 ? [['reservations', `/reservas?${new URLSearchParams(Object.entries(filters).filter(([,v]) => v))}`], ['rooms', '/acomodacoes']] : page === 2 ? [['calendar', `/reservas/calendario?ano=${month.slice(0,4)}&mes=${Number(month.slice(5))}`]] : page === 3 ? [['rooms', '/acomodacoes'], ['rates', '/tarifas']] : page === 4 ? [['calendars', '/ical'], ['emails', '/emails'], ['emailConfig', '/email/config'], ['rooms', '/acomodacoes'], ['pousada', '/pousada']] : [['pousada', '/pousada']];
      const values = await Promise.all(entries.map(async ([key,path]) => [key, await api(path)])); if (valid()) setData(Object.fromEntries(values));
    } catch (e) { if (valid()) { setData({}); setError(e.message); } } finally { if (valid()) setLoading(false); }
  }, [user, page, filters, month]);
  useEffect(() => { load(); return () => { requestGeneration.current++; }; }, [load]);
  const mutate = async (path, method, body, message = 'Alterações salvas.') => {
    const token = sessionStorage.getItem('recanto-token'); const pathname = location.pathname; const active = () => token === sessionStorage.getItem('recanto-token') && pathname === location.pathname;
    setError(''); setNotice('');
    try { const result = await api(path, method, body); if (!active()) throw new Error('A sessao ou pagina mudou.'); const failure = result.resultados?.find(r => r.sucesso === false); if (failure || result.resultado?.sucesso === false || result.falhos > 0 || result.desativado) throw new Error(failure?.erro || result.resultado?.erro || 'Revise as configuracoes e os alertas de sincronizacao.'); setNotice(message); setEditor(null); await load(); return result; } catch (e) { if (active()) setError(e.message); throw e; }
  };
  const action = (path, method, body, message) => mutate(path, method, body, message).catch(() => {});
  const remove = (path, name) => { if (window.confirm(`Excluir ${name}? Esta ação não pode ser desfeita.`)) action(path, 'DELETE'); };
  const navigate = (event, index) => { event.preventDefault(); requestGeneration.current++; history.pushState({}, '', `/painel/${slugs[index]}`); setPage(index); setEditor(null); setData({}); setNotice(''); };
  if (authLoading) return <div className="p-root p-login">Verificando sessão…</div>;
  if (!user) return <div className="p-root p-login"><div className="p-login-intro"><a href="/">RECANTO DA PAZ</a><h1>Um lugar tranquilo.<br /><em>Uma gestão presente.</em></h1><p>Reservas, acomodações e canais em um só lugar.</p></div><div className="p-login-box"><span className="p-eyebrow">ÁREA DA POUSADA</span><h2>Bem-vindo de volta</h2><p>Acesse com sua conta de gestão.</p>{error && <p role="alert" className="p-error">{error}</p>}<Editor fields={[{ label: 'E-mail', name: 'email', type: 'email', required: true, autoComplete: 'username' }, { label: 'Senha', name: 'senha', type: 'password', required: true, autoComplete: 'current-password' }]} initial={{ email: '', senha: '' }} label="Entrar" submit={async form => { const result = await api('/auth/login', 'POST', form); sessionStorage.setItem('recanto-token', result.token); setUser(result.usuario); setError(''); }} /><a href="/">← Voltar ao site</a></div></div>;
  const rooms = data.rooms || []; const alerts = Array.isArray(data.alerts) ? data.alerts : data.alerts?.alertas || [];
  return <div className="p-root p-shell"><aside className="p-sidebar"><a className="p-brand" href="/">RECANTO<br /><span>DA PAZ</span></a><span className="p-eyebrow">GESTÃO DA POUSADA</span><nav aria-label="Menu do painel">{pages.map((name,i) => <a key={name} href={`/painel/${slugs[i]}`} aria-current={page === i ? 'page' : undefined} onClick={e => navigate(e,i)}><span aria-hidden="true">{['◈','▤','▦','⌂','↻','⚙'][i]}</span>{name}</a>)}</nav><div className="p-user"><strong>{user.pousada?.nome}</strong><small>{user.email}</small><small>{write ? 'Gestão' : 'Somente visualização'}</small><button className="secondary" onClick={() => { requestGeneration.current++; sessionStorage.removeItem('recanto-token'); setLoading(false); setEditor(null); setNotice(''); setUser(null); setData({}); }}>Sair</button></div></aside>
    <main className="p-main"><header className="p-heading"><div><span className="p-eyebrow">RECANTO DA PAZ · PAINEL</span><h1>{pages[page]}</h1><p>{['O que merece sua atenção hoje.', 'Cada estadia, organizada do início ao fim.', 'Disponibilidade por noite e por acomodação.', 'Seu espaço, seus valores e suas temporadas.', 'Mantenha todos os canais em sintonia.', 'Os detalhes que fazem a pousada funcionar.'][page]}</p></div><button className="secondary" disabled={loading} onClick={load}>Atualizar</button></header>
      {!online && <p role="alert" className="p-error">Você está offline. Conecte-se para consultar ou alterar os dados.</p>}{error && <p role="alert" className="p-error">{error}</p>}{notice && <p role="status" className="p-success">{notice}</p>}{loading && <p className="p-muted" role="status">Carregando dados…</p>}
      {page === 0 && <><div className="p-stats">{[['Chegadas hoje','reservasHoje'],['Alertas críticos','alertasCriticos'],['Pendências','alertasNaoResolvidos'],['E-mails para revisar','emailsPendentes']].map(([label,key]) => <div className="p-card" key={key}><span>{label}</span><strong>{data.stats?.[key] ?? '—'}</strong></div>)}</div><h2>Atenção & próximos passos</h2>{!loading && !error && !alerts.length && <Empty>Nenhum alerta pendente.</Empty>}{alerts.map(a => { const rid = a.detalhes?.reservaId || id(a.referencia); return <article className="p-card p-alert" key={id(a)}><span className={`p-badge ${a.severidade === 'critica' ? 'cancelada' : 'pendente'}`}>{a.severidade || 'atenção'}</span><h3>{a.tipo?.replaceAll('_',' ')}</h3><p>{a.mensagem}</p>{a.tipo === 'bloqueio_manual_pendente' && <><p>Bloqueie as mesmas noites nos canais antes de confirmar.</p><div className="p-actions"><a href="https://www.airbnb.com/hosting/calendars" target="_blank" rel="noreferrer">Abrir Airbnb ↗</a><a href="https://admin.booking.com/hotel/hoteladmin/calendar" target="_blank" rel="noreferrer">Abrir Booking ↗</a>{write && rid && <button onClick={() => action(`/reservas/${rid}/bloqueio-manual`, 'PATCH', { plataformas: ['airbnb','booking'] }, 'Bloqueio manual confirmado.')}>Confirmar bloqueio</button>}</div></>}{write && a.tipo !== 'bloqueio_manual_pendente' && <button className="secondary" onClick={() => action(`/alertas/${id(a)}/resolver`, 'PATCH', {}, 'Alerta resolvido.')}>Marcar como resolvido</button>}</article>; })}</>}
      {page === 1 && <><div className="p-toolbar"><div className="p-fields"><Field label="Status" options={['',...statuses]} value={filters.status} onChange={e => setFilters({...filters,status:e.target.value})} /><Field label="Canal" options={['',...channels]} value={filters.canal} onChange={e => setFilters({...filters,canal:e.target.value})} /><Field label="De" type="date" value={filters.inicio} onChange={e => setFilters({...filters,inicio:e.target.value})} /><Field label="Até" type="date" value={filters.fim} onChange={e => setFilters({...filters,fim:e.target.value})} /></div>{write && <button onClick={() => setEditor({ kind:'reservation', value: { nome:'',telefone:'',email:'',acomodacao:'',checkin:'',checkout:'',numHospedes:2,canal:'direto',observacoes:'' } })}>Nova reserva</button>}</div>{editor?.kind === 'reservation' && <Editor title="Nova reserva" initial={editor.value} onCancel={() => setEditor(null)} label="Registrar reserva" fields={[{label:'Nome do hóspede',name:'nome',required:true},{label:'Telefone',name:'telefone',type:'tel',required:true},{label:'E-mail do hóspede',name:'email',type:'email'},{label:'Acomodação',name:'acomodacao',options:roomOptions(rooms),required:true},{label:'Entrada',name:'checkin',type:'date',required:true},{label:'Saída',name:'checkout',type:'date',required:true},{label:'Hóspedes',name:'numHospedes',type:'number',min:1,required:true},{label:'Canal da reserva',name:'canal',options:channels},{label:'Observações',name:'observacoes'}]} submit={async f => { if(f.checkout <= f.checkin) throw new Error('A saída deve ser após a entrada.'); const r = await mutate('/reservas','POST',{hospede:{nome:f.nome,telefone:f.telefone,...(f.email ? {email:f.email} : {})},acomodacao:f.acomodacao,checkin:f.checkin,checkout:f.checkout,numHospedes:f.numHospedes,canal:f.canal,origem:'manual',observacoes:f.observacoes}); setNotice(`Reserva ${r.reserva.codigo} registrada · ${money(r.preco?.total ?? r.reserva.valorTotal)}. Confira os bloqueios dos canais.`); }} />}
        <div className="p-table-wrap"><table><thead><tr>{['Reserva / hóspede','Acomodação','Estadia','Canal','Total','Status','Ações'].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{(data.reservations?.reservas || []).map(r => <tr key={id(r)}><td><strong>{r.codigo}</strong><br />{r.hospede?.nome}<small>{r.hospede?.telefone}</small></td><td>{r.acomodacao?.nome || '—'}</td><td>{date(r.checkin)}<br />{date(r.checkout)}</td><td><Badge value={r.canal} /></td><td>{money(r.valorTotal)}</td><td><Badge value={r.status} /></td><td>{write && <select aria-label={`Status de ${r.codigo}`} value={r.status} onChange={e => { const status = e.target.value; if(status !== 'cancelada' || confirm(`Cancelar a reserva ${r.codigo}?`)) action(`/reservas/${id(r)}/status`,'PATCH',{status},'Status atualizado.'); }}>{statuses.map(s => <option key={s}>{s}</option>)}</select>}</td></tr>)}</tbody></table>{!loading && !error && !data.reservations?.reservas?.length && <Empty>Nenhuma reserva para estes filtros.</Empty>}</div></>}
      {page === 2 && <><div className="p-toolbar"><Field label="Mês" type="month" value={month} onChange={e => e.target.value && setMonth(e.target.value)} /><div className="p-actions">{channels.map(c => <Badge key={c} value={c} />)}<Badge value="ical" /></div></div><p className="p-muted">Cada célula representa uma noite. O dia de saída fica disponível. Toque em uma ocupação para ver os detalhes.</p><Calendar month={month} data={data.calendar || {}} /></>}
      {page === 3 && <><div className="p-toolbar"><h2>Acomodações</h2>{write && <button onClick={() => setEditor({kind:'room',value:freshRoom})}>Nova acomodação</button>}</div>{editor?.kind === 'room' && <Editor title={id(editor.value) ? 'Editar acomodação' : 'Nova acomodação'} fields={roomFields} initial={editor.value} onCancel={() => setEditor(null)} submit={f => mutate(`/acomodacoes${f._id ? `/${f._id}` : ''}`, f._id ? 'PUT' : 'POST',f)} />}
        <div className="p-room-grid">{rooms.map(a => <article className="p-card" key={id(a)}><Badge value={a.status} /><h2>{a.nome}</h2><p>{a.tipo} · Até {a.maxHospedes} hóspedes</p><p>{a.camas}</p><strong className="p-price">{money(a.valorPadrao)} <small>/ noite</small></strong>{write && <div className="p-actions"><button className="secondary" onClick={() => setEditor({kind:'room',value:a})}>Editar {a.nome}</button><button className="danger" onClick={() => remove(`/acomodacoes/${id(a)}`,a.nome)}>Excluir</button></div>}</article>)}</div>{!loading && !error && !rooms.length && <Empty>Cadastre a primeira acomodação para receber reservas.</Empty>}
        <div className="p-toolbar"><h2>Tarifas por data</h2>{write && <><button className="secondary" onClick={() => setEditor({kind:'rate',value:{acomodacao:'',data:'',valor:0,bloqueado:'false'}})}>Nova tarifa</button><button className="secondary" onClick={() => setEditor({kind:'batch',value:{acomodacao:'',inicio:'',fim:'',valor:0,bloqueado:'false'}})}>Tarifas por período</button></>}</div>{['rate','batch'].includes(editor?.kind) && <Editor title={editor.kind === 'batch' ? 'Tarifas por período' : 'Tarifa por data'} initial={editor.value} onCancel={() => setEditor(null)} fields={[{label:'Acomodação',name:'acomodacao',options:roomOptions(rooms),required:true},...(editor.kind === 'batch' ? [{label:'Início',name:'inicio',type:'date',required:true},{label:'Fim (inclusive)',name:'fim',type:'date',required:true}] : [{label:'Data',name:'data',type:'date',required:true}]),{label:'Valor (R$)',name:'valor',type:'number',min:0,step:'.01',required:true},{label:'Disponibilidade',name:'bloqueado',options:[{value:'false',label:'Disponível'},{value:'true',label:'Bloqueada'}]}]} submit={f => { if(editor.kind === 'batch' && f.fim < f.inicio) throw new Error('O fim deve ser igual ou posterior ao início.'); return mutate(`/tarifas${editor.kind === 'batch' ? '/lote' : f._id ? `/${f._id}` : ''}`,f._id ? 'PUT':'POST',{...f,bloqueado:f.bloqueado === 'true'}); }} />}
        <div className="p-table-wrap"><table><thead><tr><th>Acomodação</th><th>Data</th><th>Valor</th><th>Disponibilidade</th><th>Ações</th></tr></thead><tbody>{(data.rates || []).map(r => <tr key={id(r)}><td>{r.acomodacao?.nome}</td><td>{date(r.data)}</td><td>{money(r.valor)}</td><td>{r.bloqueado ? 'Bloqueada' : 'Disponível'}</td><td>{write && <div className="p-actions"><button className="secondary" onClick={() => setEditor({kind:'rate',value:{...r,acomodacao:id(r.acomodacao),data:r.data.slice(0,10),bloqueado:String(r.bloqueado)}})}>Editar</button><button className="danger" onClick={() => remove(`/tarifas/${id(r)}`,'esta tarifa')}>Excluir</button></div>}</td></tr>)}</tbody></table></div></>}
      {page === 4 && <><div className="p-toolbar"><h2>Calendários iCal</h2>{write && <div className="p-actions"><button className="secondary" onClick={() => action('/ical/sincronizar','POST',{},'Sincronização iCal concluída. Confira o status dos canais.')}>Sincronizar iCal</button><button onClick={() => setEditor({kind:'ical',value:{acomodacao:'',canal:'airbnb',url:'',status:'ativo'}})}>Adicionar calendário</button></div>}</div>{editor?.kind === 'ical' && <Editor title="Calendário externo" initial={editor.value} onCancel={() => setEditor(null)} fields={[{label:'Acomodação',name:'acomodacao',options:roomOptions(rooms),required:true},{label:'Canal',name:'canal',options:channels.filter(c => c !== 'direto')},{label:'URL iCal',name:'url',type:'url',required:true},...(editor.value._id ? [{label:'Status',name:'status',options:['ativo','inativo']}] : [])]} submit={f => mutate(`/ical${f._id ? `/${f._id}` : ''}`,f._id ? 'PUT':'POST',f)} />}
        {(data.calendars || []).map(c => <article className="p-card p-sync" key={id(c)}><div><h3>{c.acomodacao?.nome} · {c.canal}</h3><p>{c.status} · Última sincronização: {c.ultimaSincronizacao ? new Date(c.ultimaSincronizacao).toLocaleString('pt-BR') : 'Ainda não sincronizado'}</p>{c.ultimoErro && <p className="p-error">{c.ultimoErro}</p>}</div>{write && <div className="p-actions"><button className="secondary" onClick={() => setEditor({kind:'ical',value:{...c,acomodacao:id(c.acomodacao)}})}>Editar</button><button className="danger" onClick={() => remove(`/ical/${id(c)}`,'este calendário')}>Excluir</button></div>}</article>)}
        <h2>Exportar disponibilidade</h2><p className="p-muted">Copie o link da acomodação na plataforma. O token permite consultar disponibilidade; compartilhe apenas com seus canais.</p>{rooms.map(a => <div className="p-card p-export" key={id(a)}><strong>{a.nome}</strong>{data.pousada?.icalToken ? <input aria-label={`Link iCal ${a.nome}`} readOnly value={`${base || location.origin}/api/ical/${id(data.pousada)}/${id(a)}.ics?token=${encodeURIComponent(data.pousada.icalToken)}`} onFocus={e => e.target.select()} /> : <p>Token de exportação indisponível.</p>}</div>)}
        <h2>E-mail de reservas</h2>{data.emailConfig && <Editor title="Conexão IMAP" disabled={!write} initial={{...data.emailConfig,ativo:String(data.emailConfig.ativo || false),pass:''}} fields={[{label:'Monitoramento',name:'ativo',options:[{value:'false',label:'Desativado'},{value:'true',label:'Ativado'}]},{label:'Servidor IMAP',name:'host',required:true},{label:'Porta TLS',name:'port',type:'number',min:1,max:65535,required:true},{label:'Usuário IMAP',name:'user',type:'email',required:true},{label:'Nova senha de aplicativo',name:'pass',type:'password',autoComplete:'new-password'}]} submit={f => mutate('/email/config','PUT',{host:f.host,port:f.port,user:f.user,ativo:f.ativo === 'true',...(f.pass ? {pass:f.pass} : {})},'Configuração de e-mail salva.')} />}<p className="p-muted">Deixe a senha em branco para manter a atual. Use uma senha de aplicativo quando seu provedor exigir.</p>
        <div className="p-toolbar"><h2>Mensagens recebidas</h2>{write && <button className="secondary" onClick={() => action('/email/sincronizar','POST',{},'Sincronização de e-mail concluída. Confira as mensagens e alertas.')}>Buscar e-mails agora</button>}</div>{(data.emails || []).map(e => <article className="p-card p-sync" key={id(e)}><div><h3>{e.assunto || 'Sem assunto'}</h3><p>{e.remetente} · {date(e.dataRecebido)} · {e.processado ? 'Processado' : 'Revisão pendente'}</p>{e.erroExtracao && <p className="p-error">{e.erroExtracao}</p>}</div>{write && <button className="secondary" onClick={() => action(`/emails/${id(e)}/reprocessar`,'POST',{},'E-mail reprocessado. Confira o resultado e os alertas.')}>Reprocessar</button>}</article>)}{!loading && !error && !data.emails?.length && <Empty>Nenhum e-mail recebido.</Empty>}</>}
      {page === 5 && <>{data.pousada && <Editor title="Dados da pousada" disabled={!write} initial={{...data.pousada,whatsappAtivo:String(data.pousada.whatsappAtivo || false)}} fields={[{label:'Nome da pousada',name:'nome',required:true},{label:'E-mail da pousada',name:'email',type:'email',required:true},{label:'WhatsApp da pousada',name:'whatsapp',type:'tel',required:true},{label:'Endere\u00e7o',name:'endereco'},{label:'Notificações WhatsApp',name:'whatsappAtivo',options:[{value:'false',label:'Desativadas'},{value:'true',label:'Ativadas'}]}]} submit={f => mutate('/pousada','PUT',{nome:f.nome,email:f.email,whatsapp:f.whatsapp,endereco:f.endereco || '',whatsappAtivo:f.whatsappAtivo === 'true'})} />}{write && <div className="p-card"><h2>Token iCal</h2><p>Gerar um novo token invalida os links de exportação anteriores. Atualize os links em cada plataforma depois da troca.</p><button className="secondary" onClick={() => { if(confirm('Invalidar os links atuais e gerar um novo token iCal?')) action('/pousada/ical-token','POST',{},'Novo token gerado. Atualize os links nas plataformas.'); }}>Gerar novo token iCal</button></div>}<Editor title="Alterar senha" initial={{senhaAtual:'',novaSenha:'',confirmarSenha:''}} fields={[{label:'Senha atual',name:'senhaAtual',type:'password',autoComplete:'current-password',required:true},{label:'Nova senha',name:'novaSenha',type:'password',autoComplete:'new-password',minLength:10,required:true},{label:'Confirmar nova senha',name:'confirmarSenha',type:'password',autoComplete:'new-password',minLength:10,required:true}]} submit={f => { if(f.novaSenha !== f.confirmarSenha) throw new Error('As novas senhas devem ser iguais.'); return mutate('/auth/trocar-senha','POST',f,'Senha alterada com sucesso.'); }} /></>}
      <footer className="p-footer">Pousada Recanto da Paz · Cuidar de cada estadia.</footer>
    </main></div>;
}
function Empty({children}) { return <div className="p-empty">{children}</div>; }
function Badge({value}) { return <span className={`p-badge ${value}`}>{value}</span>; }
function Calendar({ month, data }) {
  const [selected,setSelected] = useState(null); const [year,m] = month.split('-').map(Number); const days = new Date(Date.UTC(year,m,0)).getUTCDate();
  return <><div className="p-table-wrap"><table className="p-calendar"><thead><tr><th>Acomodação</th>{Array.from({length:days},(_,i) => <th key={i}>{i+1}<small>{new Date(Date.UTC(year,m-1,i+1)).toLocaleDateString('pt-BR',{weekday:'short',timeZone:'UTC'})}</small></th>)}</tr></thead><tbody>{Object.entries(data).map(([key,a]) => <tr key={key}><th>{a.nome}</th>{Array.from({length:days},(_,i) => { const d = `${month}-${String(i+1).padStart(2,'0')}`; const raw = a.dias?.[d]; const occupants = Array.isArray(raw) ? raw : raw?.eventos || (raw ? [raw] : []); return <td key={d}>{occupants.length ? <button className={`p-cell ${occupants[0].canal || 'ical'} ${raw?.conflito ? 'conflito' : ''}`} aria-label={`${a.nome}, ${date(d)}, ${occupants.map(o => o.canal || o.origem || 'ocupada').join(', ')}`} onClick={() => setSelected({nome:a.nome,data:d,occupants})}>{occupants.length > 1 ? occupants.length : '●'}</button> : <span className="p-free" aria-label={`${a.nome}, ${date(d)}, disponível`}>·</span>}</td>; })}</tr>)}</tbody></table></div>{!Object.keys(data).length && <Empty>Nenhuma acomodação no calendário.</Empty>}{selected && <div className="p-card"><h2>{selected.nome} · {date(selected.data)}</h2>{selected.occupants.map((o,i) => <p key={i}><Badge value={o.canal || o.origem || 'ical'} /> {o.codigo} {o.hospede} {o.status}</p>)}<button className="secondary" onClick={() => setSelected(null)}>Fechar detalhes</button></div>}</>;
}
