import express from 'express';
import cors from 'cors';
import mongoose from 'mongoose';
import authRoutes from './routes/auth.js';
import acomodacaoRoutes from './routes/acomodacoes.js';
import reservaRoutes from './routes/reservas.js';
import icalRoutes from './routes/ical.js';
import emailRoutes from './routes/email.js';
import alertaRoutes from './routes/alertas.js';
import syncRoutes from './routes/sync.js';
import pousadaRoutes from './routes/pousada.js';
import publicoRoutes from './routes/publico.js';
import { exportarICal } from './controllers/icalController.js';
import { icalExportLimiter, apiLimiter } from './middleware/rateLimit.js';
import { authMiddleware } from './middleware/auth.js';
import { multiTenant } from './middleware/multiTenant.js';
import { escritaPermitida } from './middleware/cron.js';
const app = express();
app.disable('x-powered-by');
if (process.env.TRUST_PROXY) app.set('trust proxy', Number(process.env.TRUST_PROXY));
app.use(cors({ origin: (origin, cb) => { const allowed = (process.env.ALLOWED_ORIGINS || process.env.FRONTEND_URL || 'http://localhost:5173,http://127.0.0.1:5173').split(',').map(s => s.trim()); cb(null, !origin || allowed.includes(origin)); } }));
app.use(express.json({ limit: '100kb' }));
app.use((req, res, next) => { res.set('Cache-Control', 'no-store'); res.set('X-Content-Type-Options', 'nosniff'); next(); });
const health = (_req, res) => res.status(mongoose.connection.readyState === 1 ? 200 : 503).json({ ok: mongoose.connection.readyState === 1, timestamp: new Date() });
app.get('/health', health); app.get('/api/health', health);
app.use('/api/auth', authRoutes);
app.use('/api/sync', syncRoutes);
app.use('/api/publico', publicoRoutes);
app.get(['/ical/:pousadaId/:acomodacaoId.ics','/api/ical/:pousadaId/:acomodacaoId.ics'], icalExportLimiter, exportarICal);
app.use('/api', apiLimiter, authMiddleware, multiTenant, escritaPermitida);
app.use('/api/pousada', pousadaRoutes);
app.use('/api', acomodacaoRoutes, reservaRoutes, icalRoutes, emailRoutes, alertaRoutes);
app.use((_req, res) => res.status(404).json({ erro: 'Rota não encontrada' }));
app.use((err, _req, res, _next) => {
  const status = err.status || (['ValidationError','CastError'].includes(err.name) ? 400 : err.code === 11000 ? 409 : 500);
  if (status === 500) console.error('Falha na API:', err.name);
  res.status(status).json({ erro: status < 500 ? err.message : 'Erro interno do servidor' });
});
export default app;
